services:
  frontend:
    build: src/frontend
    ports:
      - "17001:80" # main http frontend port
  users:
    build: src/users
    expose:
      - "80" # http server for REST --
    ports:
      - "17002:80" # only forward for debugging
  posts:
    build: src/posts
    expose: 
     - "50551" # grpc server
    ports:
      - "17051:50051"

